pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:davipro_34/plusoumoins.git
          - cd plusoumoins.git
          - git push --mirror git@github.com:davipro34/plusOuMoins.git